### ISSUE TITLE
Run build and commit first?

### ISSUE THREAD

**Issue by developit** [bjoerge/cut-release#14]
Question: I often have an `npm-script` called `build`. Usually this is invoked via a `prepublish` script, but I was curious if it would be possible (or in your interest) to run a script prior to publishing, perhaps committing any resulting changes along with the version change?  Not sure if this is covered by one of the existing `pre/post-` hooks.

**Comment by jamestalmage** [comment]
See https://docs.npmjs.com/cli/version

I think you are looking for `preversion` and `postversion` scripts. They work great with `cut-release`.

**Comment by jamestalmage** [comment]
See also: https://github.com/npm/npm/issues/8620

**Comment by developit** [comment]
@jamestalmage perfect! I was thinking there would be a simple way to do this with hooks, thanks.
