### ISSUE TITLE
When only one version of a module is published cut-release doesn't work

### ISSUE THREAD

**Issue by koresar** [bjoerge/cut-release#15]
In [this line](https://github.com/bjoerge/cut-release/blob/master/bin/cut-release.js#L129) it is expected that `npm show . versions` prints a JSON array. In case a module was published only once the command prints non-JSON.

```
$ npm show . versions
1.0.0
$
```

Thus cut-release crashes on `JSON.parse`.

**Comment by jamestalmage** [comment]
I routinely use `cut-release` for publishing the first/second/third version. Something else is going on here.

**Comment by koresar** [comment]
Oh, forgot to mention. I was doing the `cut-release -t rc`, then selected `premajor`, then it crashed. I think.

**Comment by jamestalmage** [comment]
OK, I never use that feature. Not sure who wrote it.

If you've got a plan to fix it, go ahead and submit a PR. Just make sure you write failing tests that are fixed by your changes.
